In [3]:
import kagglehub
import pandas as pd
from pathlib import Path
import os
import geopandas
import matplotlib.pyplot as plt
from shapely.geometry import Point

'''
This will prompt for kaggle.json path or use default ~/.kaggle/kaggle.json.
For me this is saved locally on my machine. You will need to setup your own api key at Kaggle to grab the code:
https://www.kaggle.com/docs/api#interacting-with-datasets
'''
kagglehub.login(r"C:\Users\nrdee\Documents\Data\Data Science Masters\Data 780\kaggle.json")
path = kagglehub.dataset_download("camnugent/california-housing-prices")
print("Path to dataset files:", path)

csv_path = os.path.join(path, "housing.csv")
cali_df = pd.read_csv(csv_path)
cali_df.head(20)

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggleâ€¦

Path to dataset files: C:\Users\nrdee\.cache\kagglehub\datasets\camnugent\california-housing-prices\versions\1

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
5,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0,NEAR BAY
6,-122.25,37.84,52.0,2535.0,489.0,1094.0,514.0,3.6591,299200.0,NEAR BAY
7,-122.25,37.84,52.0,3104.0,687.0,1157.0,647.0,3.1200,241400.0,NEAR BAY
8,-122.26,37.84,42.0,2555.0,665.0,1206.0,595.0,2.0804,226700.0,NEAR BAY
9,-122.25,37.84,52.0,3549.0,707.0,1551.0,714.0,3.6912,261100.0,NEAR BAY
10,-122.26,37.85,52.0,2202.0,434.0,910.0,402.0,3.2031,281500.0,NEAR BAY
11,-122.26,37.85,52.0,3503.0,752.0,1504.0,734.0,3.2705,241800.0,NEAR BAY
12,-122.26,37.85,52.0,2491.0,474.0,1098.0,468.0,3.0750,213500.0,NEAR BAY
13,-122.26,37.84,52.0,696.0,191.0,345.0,174.0,2.6736,191300.0,NEAR BAY
14,-122.26,37.85,52.0,2643.0,626.0,1212.0,620.0,1.9167,159200.0,NEAR BAY
15,-122.26,37.85,50.0,1120.0,283.0,697.0,264.0,2.1250,140000.0,NEAR BAY
16,-122.27,37.85,52.0,1966.0,347.0,793.0,331.0,2.7750,152500.0,NEAR BAY
17,-122.27,37.85,52.0,1228.0,293.0,648.0,303.0,2.1202,155500.0,NEAR BAY
18,-122.26,37.84,50.0,2239.0,455.0,990.0,419.0,1.9911,158700.0,NEAR BAY
19,-122.27,37.84,52.0,1503.0,298.0,690.0,275.0,2.6033,162900.0,NEAR BAY

In [2]:
import folium
import branca.colormap as cm
from folium.plugins import MarkerCluster

cali_df = cali_df.dropna(subset=["latitude", "longitude", "median_house_value"])

#set up color scale
min_val = cali_df["median_house_value"].min()
max_val = cali_df["median_house_value"].max()

#color filter, find more info here: https://python-visualization.github.io/folium/latest/advanced_guide/colormaps.html
colormap = cm.linear.YlOrRd_09.scale(min_val, max_val)

#create map
m = folium.Map(location=[36.7783, -119.4179], zoom_start=6)

#add colored circles
for _, row in cali_df.iterrows():
    folium.CircleMarker(
        location=[row["latitude"], row["longitude"]],
        radius=4,
        color=colormap(row["median_house_value"]),
        fill=True,
        fill_opacity=0.7,
        popup=f"${row['median_house_value']:,.0f}"
    ).add_to(m)

#add color legend to map
colormap.caption = "Median House Value"
colormap.add_to(m)

#save map
m.save("california_colored_prices.html")

In [5]:
cali_df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000